const painRules = [
  ['CURRENT_SEARCH_TOOL_FAILED', /(google photos|iphone photos|apple photos|search).{0,30}(doesn.t|does not|isn.t|not working|failed|can.t)/i],
  ['SCREENSHOT_SEARCH', /screenshot/i], ['VIDEO_SEARCH', /video|clip|footage/i], ['PRIVACY_CONCERN', /private|privacy|upload|cloud|on.device/i],
  ['DOCUMENT_SEARCH', /receipt|document|invoice|ticket/i], ['DATE_UNKNOWN', /don.t remember (the )?date|without (remembering|knowing) (the )?date|when i took/i],
  ['TOO_MANY_PHOTOS', /too many|thousands|[1-9][0-9],[0-9]{3}|massive|huge camera roll/i], ['PHOTO_ORGANIZATION', /organi[sz]|album|folder|sort|manage/i],
  ['ACTIVITY_SEARCH', /playing|walking|running|dancing|swimming|activity/i], ['OBJECT_SEARCH', /dog|cat|car|shirt|object|wearing|beach/i],
  ['PHOTO_SEARCH', /photo|picture|camera roll|image/i]
];
const exclusions=[['MIGRATION',/(?:migrat|mov(?:e|ing|ed).{0,30}(?:drive|library)|upgrad(?:e|ing).{0,30}(?:drive|disk))/i],['FILE_LOCATION',/(?:where (?:are|is).{0,30}(?:stored|located)|file path|folder location|original files)/i],['STORAGE_SIZE',/(?:total size|storage (?:space|usage|full)|free up space|disk space)/i],['BACKUP',/\bbackup|back up|restore\b/i],['SYNC_FAILURE',/\bsync(?:ing)? (?:fail|error|issue|problem)|won't sync|not sync/i],['CORRUPTION',/corrupt(?:ed|ion)?/i],['RECOVERY',/(?:recover|recovery|undelete|deleted photos?)/i],['DUPLICATE_FILES',/(?<!not )duplicates?|deduplicat/i],['PHOTO_EDITING',/(?:lightroom|photoshop|edit(?:ing)?|raw\+?jpeg)/i],['CAMERA_HARDWARE',/(?:camera|lens|sensor|shutter).{0,25}(?:hardware|broken|recommend|best|issue)/i],['PHOTO_LIBRARY_SOFTWARE_CONFIGURATION',/(?:digiKam|lightroom|photo manager).{0,50}(?:config|setting|script|upgrade|catalog)/i],['SERVER_STORAGE',/(?:server|nas|rclone|temp-dir|workdir).{0,50}(?:storage|directory|error|sync|mount)/i],['FILESYSTEM',/(?:filesystem|file system|directory|folder|hard drive|disk|mount)/i],['PERMISSIONS_TECH_SUPPORT',/(?:permission denied|access denied|not authorized|technical support)/i]];
const supported=[['UNKNOWN_DATE_SEARCH',/(?:don.t|cannot|can't|can not) remember (?:the )?(?:date|when)|without (?:knowing|remembering) (?:the )?(?:date|when)|not sure when (?:i|it)/i,'Search by remembered details instead of capture date'],['DESCRIPTION_BASED_SEARCH',/(?:search|find).{0,45}(?:by (?:a )?description|by describing|what(?:'s| is) in (?:it|the (?:photo|picture|image))|what i remember)|natural.language.{0,25}(?:photo|video|media) search/i,'Natural-language, on-device photo and video search'],['SCREENSHOT_CONTENT_SEARCH',/(?:find|search).{0,35}screenshot.{0,50}(?:text|word|content|remember|inside)|screenshot.{0,35}(?:by|from).{0,25}(?:text|word|content)/i,'Screenshot search using remembered text or visual content'],['VIDEO_CONTENT_SEARCH',/(?:find|search).{0,35}(?:video|clip|footage).{0,60}(?:happen|moment|scene|describe|remember)|(?:video|clip).{0,35}(?:by description|what happened)/i,'Video search using a remembered scene or moment'],['LARGE_LIBRARY_SEARCH',/(?:thousands|[1-9][0-9],[0-9]{3}|large|huge).{0,35}(?:photos|pictures|camera roll|library).{0,70}(?:can't|cannot|find|search|scroll)|(?:can't|cannot|struggl).{0,50}(?:find|search).{0,50}(?:thousands|large|huge).{0,25}(?:photos|library)/i,'Description search across a large local media library'],['CURRENT_VISUAL_SEARCH_FAILED',/(?:apple photos|iphone photos|google photos|gallery|photo search).{0,45}(?:search.{0,15})?(?:doesn.t work|does not work|isn.t working|failed|can.t find|cannot find).{0,60}(?:photo|picture|video|screenshot|what i remember)/i,'More descriptive local search when the current visual search fails'],['OBJECT_SEARCH',/(?:find|search).{0,35}(?:photo|picture|image).{0,45}(?:my |a |the )?(?:dog|cat|car|person|shirt|object)/i,'Search photos by a remembered object'],['SCENE_SEARCH',/(?:find|search).{0,35}(?:photo|picture|image).{0,55}(?:beach|park|outside|inside|sunset|snow|scene)/i,'Search photos by a remembered scene'],['ACTIVITY_SEARCH',/(?:find|search).{0,35}(?:photo|picture|video).{0,55}(?:playing|walking|running|dancing|swimming|activity)/i,'Search media by a remembered activity'],['NATURAL_LANGUAGE_MEDIA_SEARCH',/(?:is there an app|how (?:do|can) i).{0,35}(?:find|search).{0,45}(?:old |specific )?(?:photo|picture|video|screenshot).{0,50}(?:remember|description|camera roll|library)/i,'Natural-language, on-device media search']];

export class ProductFitClassifier {
  constructor({minimum=80}={}){this.minimum=minimum;}
  classify(text){const exclusion=exclusions.find(([,rule])=>rule.test(text))?.[0]||null;const matches=supported.filter(([,rule])=>rule.test(text));const primary=matches[0];if(primary&&!exclusion)return{productFitScore:matches.length>1?96:90,entailment:'YES',supportedSearchNeed:primary[0],excludedProblem:null,honorableFeature:primary[2],fitReason:`The user explicitly needs ${primary[0].toLowerCase().replaceAll('_',' ')}, which Honorable's current local media search supports.`};if(primary&&exclusion){const explicit=matches.length>1||/(?:what i remember|by describ|don't remember|cannot remember|can't remember|thousands.{0,30}(?:can't|cannot) find)/i.test(text);if(explicit)return{productFitScore:85,entailment:'YES',supportedSearchNeed:primary[0],excludedProblem:exclusion,honorableFeature:primary[2],fitReason:`A ${exclusion.toLowerCase().replaceAll('_',' ')} issue is present, but the post also states a supported media-search need.`};}if(exclusion)return{productFitScore:10,entailment:'NO',supportedSearchNeed:null,excludedProblem:exclusion,honorableFeature:null,fitReason:`This is a ${exclusion.toLowerCase().replaceAll('_',' ')} problem; Honorable does not solve it.`};if(/(?:find|search|scroll|remember).{0,50}(?:photo|picture|video|screenshot|camera roll)|(?:photo|picture|video|screenshot).{0,50}(?:find|search|scroll|remember)/i.test(text))return{productFitScore:55,entailment:'UNCERTAIN',supportedSearchNeed:null,excludedProblem:null,honorableFeature:null,fitReason:'The post mentions media retrieval, but does not state a search need supported by Honorable clearly enough.'};return{productFitScore:0,entailment:'NO',supportedSearchNeed:null,excludedProblem:null,honorableFeature:null,fitReason:'No supported Honorable media-search need is stated.'};}
}

export class IntentClassifier {
  classify(text) {
    const value = text.toLowerCase();
    const veryHigh = /(spent (an|\d+) hours?|[1-9][0-9],[0-9]{3}|tens of thousands|desperate|can never find|cannot find).{0,80}(photo|picture|video|screenshot)|(?:photo|picture|video|screenshot).{0,80}(spent (an|\d+) hours?|can never find|cannot find)/i.test(value);
    const high = /(can't find|cannot find|need (to find|one)|how do .* find|is there an app|search .* photos|search .* videos|does not upload|don't remember .* date|search isn't working)/i.test(value);
    const medium = /(best way|organize|sort|manage|too many|advice)/i.test(value);
    const irrelevant=/(best camera|camera lens|landscape photography|photo editing preset)/i.test(value);
    return irrelevant?'IRRELEVANT':veryHigh?'VERY HIGH':high?'HIGH':medium?'MEDIUM':'LOW';
  }
  painPoint(text) { return painRules.find(([, rule]) => rule.test(text))?.[0] || 'OTHER'; }
}

export class OpportunityAnalyzer {
  constructor(classifier = new IntentClassifier(), now = () => new Date(),productFit=new ProductFitClassifier()) { this.classifier = classifier; this.now = now;this.productFit=productFit; }
  analyze(item) {
    const intent = this.classifier.classify(`${item.topic} ${item.text}`);
    const painPoint = this.classifier.painPoint(`${item.topic} ${item.text}`);
    const relevance = /find|search|scroll|remember|organi[sz]|photo|video|screenshot|private/i.test(`${item.topic} ${item.text}`) ? .92 : .35;
    const intentValue = { 'VERY HIGH':1, 'HIGH':.86, 'MEDIUM':.58, 'LOW':.2, 'IRRELEVANT':0 }[intent];
    const ageDays = Math.max(0, (this.now() - new Date(item.publishedAt)) / 86400000);
    const recency = Math.max(.15, 1 - ageDays / 30);
    const engagement = Math.min(1, Math.log10((item.engagement || 0) + 1) / 3);
    const platform = ({ Reddit:.95, YouTube:.9, TikTok:.86, Instagram:.78 }[item.platform] || .65);
    const score = Math.round(100 * (relevance*.30 + intentValue*.25 + recency*.15 + engagement*.10 + platform*.08 + (item.audienceFit || .5)*.12));
    const fit=this.productFit.classify(`${item.topic||''} ${item.text||''}`);return { ...item, sourceType:item.sourceType||(item.dataType==='MOCK'?'MOCK':'DIRECT_API'), intent, painPoint, problemDetected:this.problem(painPoint),userProblem:this.problem(painPoint),...fit,whyItFits:fit.fitReason,relevanceScore:Math.round(relevance*100),intentScore:Math.round(intentValue*100),recencyScore:Math.round(recency*100),overallOpportunityScore:score,score, scoring:{ problemRelevance:relevance, intent:intentValue, recency, engagement, platform, audienceFit:item.audienceFit || .5 }, angle:this.angle(painPoint, intent) };
  }
  angle(pain, intent) {
    const angles = { PHOTO_SEARCH:'Show one natural-language query replacing endless scrolling.', VIDEO_SEARCH:'Demo finding a precise remembered video moment.', SCREENSHOT_SEARCH:'Show finding a screenshot from the words or scene remembered.', PRIVACY_CONCERN:'Lead with on-device search and “Your memories stay yours.”', PHOTO_ORGANIZATION:'Position search as an alternative to maintaining albums.', DATE_UNKNOWN:'Describe what you remember instead of searching by date.', TOO_MANY_PHOTOS:'Focus on navigating a huge existing library.', DOCUMENT_SEARCH:'Demo retrieving a receipt or document screenshot by description.', CURRENT_SEARCH_TOOL_FAILED:'Acknowledge the limitation and demonstrate a more descriptive query.', OBJECT_SEARCH:'Use the remembered object, person, or setting as the query.', ACTIVITY_SEARCH:'Use the remembered activity as the query.', OTHER:'Demonstrate the remembered-moment workflow.' };
    return `${angles[pain]||angles.OTHER} ${['VERY HIGH','HIGH'].includes(intent) ? 'A short, transparent waitlist mention is relevant.' : 'Lead with useful context before any CTA.'}`;
  }
  problem(pain){return ({PHOTO_SEARCH:'Cannot locate a remembered photo',VIDEO_SEARCH:'Cannot locate a remembered video',SCREENSHOT_SEARCH:'Cannot locate a screenshot',TOO_MANY_PHOTOS:'Large camera roll is difficult to navigate',DATE_UNKNOWN:'Does not remember when media was captured',OBJECT_SEARCH:'Needs description-based object search',ACTIVITY_SEARCH:'Needs description-based activity search',DOCUMENT_SEARCH:'Cannot retrieve a saved document or receipt',PHOTO_ORGANIZATION:'Photo organization is burdensome',PRIVACY_CONCERN:'Wants private photo search',CURRENT_SEARCH_TOOL_FAILED:'Current photo search did not meet the need',OTHER:'Potential media retrieval problem'})[pain]||'Potential media retrieval problem';}
}

export class TrendAnalyzer {
  summarize(opportunities) {
    const counts = opportunities.reduce((all, x) => ((all[x.painPoint] = (all[x.painPoint] || 0) + 1), all), {});
    return Object.entries(counts).sort((a,b) => b[1]-a[1]).map(([painPoint,count]) => ({ painPoint,count,share:Math.round(count/opportunities.length*100) || 0 }));
  }
}
