import crypto from 'node:crypto';

export const AutoReplyMode=Object.freeze({OFF:'OFF',APPROVAL_REQUIRED:'APPROVAL_REQUIRED',HIGH_CONFIDENCE_AUTO:'HIGH_CONFIDENCE_AUTO',MANUAL_ASSIST:'MANUAL_ASSIST'});
export const defaultLimits=Object.freeze({hourly:2,daily:6,minIntervalMinutes:20,perConversation:1,perAuthor:1});
const sensitive=/(suicid|self.harm|funeral|died|death|grief|cancer|hospital|medical|emergency|abuse|minor|child safety|politic|election|war|crisis)/i;
const promotionRestricted=/(no promotion|no self.promotion|no advertising|no ads|spam prohibited)/i;
const honorableComplaint=/(honorable).{0,40}(broken|scam|bad|complaint|refund|hate|problem)/i;
const normalize=value=>String(value||'').toLowerCase().replace(/https?:\/\/\S+/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');

export class AutoReplyEngine {
  constructor({store,responseGenerator,config={},now=()=>new Date()}){this.store=store;this.responseGenerator=responseGenerator;this.now=now;this.config=config;}
  platformConfig(platform){const key=platform.toLowerCase().split('/')[0];return this.config.platforms?.[key]||{mode:AutoReplyMode.APPROVAL_REQUIRED,authenticated:false,apiSupport:'MANUAL_ASSIST',limits:defaultLimits,paused:false};}
  score(opportunity){const intent={'VERY HIGH':100,VERY_HIGH:100,HIGH:85,MEDIUM:45,LOW:10}[opportunity.intent]||0;const suitability=/Reddit|YouTube|Instagram|Facebook/i.test(opportunity.platform)?80:55;const promotion=promotionRestricted.test(`${opportunity.topic} ${opportunity.text}`)?0:90;return Math.round((opportunity.relevanceScore*.25+intent*.25+opportunity.score*.25+suitability*.15+promotion*.10));}
  async evaluate(opportunity){
    const snapshot=await this.store.snapshot();const key=opportunity.platform.toLowerCase().split('/')[0];const platform={...this.platformConfig(opportunity.platform),...(snapshot.autoReplySettings?.platforms?.[key]||{})};const text=`${opportunity.topic||''} ${opportunity.text||''}`;const autoReplyScore=this.score(opportunity);const recent=(snapshot.autoReplyAudit||[]).filter(x=>x.postingResult==='POSTED');const targetHash=hash(opportunity.sourceUrl||opportunity.id);const reply=this.responseGenerator.generateAutoReply(opportunity);const replyHash=hash(normalize(reply));const now=this.now();const today=recent.filter(x=>x.platform===opportunity.platform&&new Date(x.timestamp).toDateString()===now.toDateString());const hour=recent.filter(x=>x.platform===opportunity.platform&&now-new Date(x.timestamp)<3600000);const last=recent.filter(x=>x.platform===opportunity.platform).sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp))[0];
    const reasons=[];if((snapshot.autoReplySettings?.globalEnabled??false)!==true)reasons.push('GLOBAL_DISABLED');if(snapshot.autoReplySettings?.killSwitch)reasons.push('KILL_SWITCH');if(platform.paused)reasons.push('PLATFORM_PAUSED');if(platform.mode!==AutoReplyMode.HIGH_CONFIDENCE_AUTO)reasons.push('MODE_REQUIRES_REVIEW');if(!platform.authenticated)reasons.push('ACCOUNT_NOT_AUTHENTICATED');if(platform.apiSupport!=='REPLY_API_SUPPORTED')reasons.push('REPLY_API_NOT_VERIFIED');if(!['VERY HIGH','VERY_HIGH','HIGH'].includes(opportunity.intent))reasons.push('INTENT_TOO_LOW');if(opportunity.entailment!=='YES')reasons.push('PRODUCT_ENTAILMENT_NOT_YES');if(Number(opportunity.productFitScore||0)<(this.config.productFitThreshold||80))reasons.push('PRODUCT_FIT_TOO_LOW');if(opportunity.relevanceScore<(this.config.relevanceThreshold||85))reasons.push('RELEVANCE_TOO_LOW');if(autoReplyScore<(this.config.autoReplyThreshold||88))reasons.push('AUTO_REPLY_SCORE_TOO_LOW');if(this.responseGenerator.outreachStatus()!=='READY_FOR_REVIEW')reasons.push('BLOCKED_NO_PUBLIC_WAITLIST_URL');if(opportunity.mock||opportunity.dataType==='MOCK')reasons.push('NOT_LIVE_PUBLIC_POST');if(!opportunity.sourceUrl)reasons.push('NO_PUBLIC_URL');if(sensitive.test(text))reasons.push('SENSITIVE_TOPIC');if(promotionRestricted.test(text))reasons.push('PROMOTION_RESTRICTED');if(honorableComplaint.test(text))reasons.push('HONORABLE_COMPLAINT');if(recent.some(x=>x.targetHash===targetHash))reasons.push('TARGET_ALREADY_REPLIED');if(recent.some(x=>x.replyHash===replyHash&&now-new Date(x.timestamp)<30*86400000))reasons.push('SIMILAR_REPLY_RECENTLY_USED');const limits={...defaultLimits,...platform.limits};if(hour.length>=limits.hourly)reasons.push('HOURLY_LIMIT');if(today.length>=limits.daily)reasons.push('DAILY_LIMIT');if(last&&now-new Date(last.timestamp)<limits.minIntervalMinutes*60000)reasons.push('MIN_INTERVAL');
    return {opportunityId:opportunity.id,platform:opportunity.platform,targetUrl:opportunity.sourceUrl,targetHash,reply,replyHash,opportunityScore:opportunity.score,autoReplyScore,eligible:reasons.length===0,reasons,mode:platform.mode,dryRun:this.config.dryRun!==false,status:reasons.length?'APPROVAL_QUEUE':'READY'};
  }
  async dryRun(opportunities){const proposals=[];for(const opportunity of opportunities.slice(0,100)){const evaluated=await this.evaluate(opportunity);if(['VERY HIGH','VERY_HIGH','HIGH'].includes(opportunity.intent))proposals.push(evaluated);}const selected=proposals.sort((a,b)=>b.autoReplyScore-a.autoReplyScore).slice(0,20);await this.store.saveAutoReplyProposals(selected);for(const item of selected)await this.store.addAutoReplyAudit({...item,postingResult:'SIMULATED_NOT_POSTED',allowedReason:item.eligible?'ALL_SAFETY_GATES_PASSED':item.reasons.join(',')});return selected;}
}

export function platformCapabilities(settings={}){return[
  {platform:'Instagram',mode:settings.instagram?.mode||AutoReplyMode.MANUAL_ASSIST,authenticated:Boolean(settings.instagram?.authenticated),apiSupport:settings.instagram?.apiSupport||'MANUAL_ASSIST'},
  {platform:'Facebook',mode:settings.facebook?.mode||AutoReplyMode.MANUAL_ASSIST,authenticated:Boolean(settings.facebook?.authenticated),apiSupport:settings.facebook?.apiSupport||'MANUAL_ASSIST'},
  {platform:'YouTube',mode:settings.youtube?.mode||AutoReplyMode.APPROVAL_REQUIRED,authenticated:Boolean(settings.youtube?.authenticated),apiSupport:settings.youtube?.apiSupport||'APPROVAL_REQUIRED'},
  {platform:'Reddit',mode:settings.reddit?.mode||AutoReplyMode.MANUAL_ASSIST,authenticated:Boolean(settings.reddit?.authenticated),apiSupport:settings.reddit?.apiSupport||'MANUAL_ASSIST'},
  {platform:'TikTok',mode:AutoReplyMode.MANUAL_ASSIST,authenticated:false,apiSupport:'REPLY_API_NOT_SUPPORTED'}
].map(x=>({...x,limits:defaultLimits,paused:false}));}
