use_default_settings:
  engines:
    keep_only:
      - brave

general:
  debug: false
  instance_name: "Honorable Local Search"

search:
  safe_search: 1
  autocomplete: ""
  formats:
    - html
    - json

server:
  limiter: false
  public_instance: false
  image_proxy: false
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Robots-Tag: "noindex, nofollow"
    Referrer-Policy: no-referrer

outgoing:
  request_timeout: 4.0
  max_request_timeout: 8.0
