import { pathToFileURL } from 'node:url';
import { isQualityPublicProblem } from '../src/core/discovery.js';
import { OpportunityAnalyzer } from '../src/core/analysis.js';

function diagnoseResults(results=[]){const rejected={IRRELEVANT:0,LOW_INTENT:0,DUPLICATE:0,SEO_CONTENT:0,PRODUCT_PAGE:0,NO_USER_PROBLEM:0,OTHER:0};const seen=new Set();let accepted=0;const analyzer=new OpportunityAnalyzer();for(const result of results){const sourceUrl=result.url||result.link||'';const topic=result.title||'';const text=result.content||result.snippet||'';if(seen.has(sourceUrl)){rejected.DUPLICATE++;continue;}seen.add(sourceUrl);const item={sourceType:'PUBLIC_WEB',sourceUrl,topic,text,publishedAt:result.publishedDate||null,platform:'Forums/Public Web',engagement:0};if(!isQualityPublicProblem(item)){if(/top \d+|best .* apps?|affiliate|sponsored/i.test(`${topic} ${text}`))rejected.SEO_CONTENT++;else if(/pricing|buy now|download .*app|product page/i.test(`${topic} ${text}`))rejected.PRODUCT_PAGE++;else rejected.NO_USER_PROBLEM++;continue;}const analyzed=analyzer.analyze(item);if(analyzed.intent==='IRRELEVANT')rejected.IRRELEVANT++;else if(analyzed.intent==='LOW')rejected.LOW_INTENT++;else accepted++;}return{accepted,rejected};}

export async function webStatus(env=process.env,fetchImpl=fetch){
  if(env.SEARXNG_BASE_URL){const base={provider:'SEARXNG',baseUrl:true,apiKey:Boolean(env.GOOGLE_SEARCH_API_KEY),engineId:Boolean(env.GOOGLE_SEARCH_ENGINE_ID)};let url;try{url=new URL('/search',env.SEARXNG_BASE_URL);}catch{return{...base,searxng:'NOT_CONFIGURED',liveRequest:'FAIL',rawResults:0,honorableResults:0,reason:'MALFORMED_BASE_URL'};}url.search=new URLSearchParams({q:'"can\'t find an old photo" OR "how do I find an old photo"',format:'json',language:'en',safesearch:'1',time_range:'month'}).toString();try{const response=await fetchImpl(url,{headers:{accept:'application/json'},signal:AbortSignal.timeout(8000)});if(!response.ok)return{...base,searxng:'DOWN',httpStatus:response.status,liveRequest:'FAIL',rawResults:0,honorableResults:0,reason:`HTTP_${response.status}`};const payload=await response.json();if(!Array.isArray(payload.results))return{...base,searxng:'RUNNING',httpStatus:response.status,liveRequest:'FAIL',rawResults:0,honorableResults:0,reason:'INVALID_RESPONSE'};const diagnosis=diagnoseResults(payload.results);const unavailable=(payload.unresponsive_engines||[]).map(x=>Array.isArray(x)?x[0]:x);return{...base,searxng:'RUNNING',httpStatus:response.status,liveRequest:'PASS',rawResults:payload.results.length,honorableResults:diagnosis.accepted,rejected:diagnosis.rejected,reason:payload.results.length?'NONE':unavailable.length?`UPSTREAM_ENGINE_UNRESPONSIVE: ${unavailable.join(', ')}`:'NO_RESULTS'};}catch(error){return{...base,searxng:'DOWN',liveRequest:'FAIL',rawResults:0,honorableResults:0,reason:error?.name==='TimeoutError'?'TIMEOUT':'NETWORK_FAILURE'};}}
  const apiKey=Boolean(env.GOOGLE_SEARCH_API_KEY);const engineId=Boolean(env.GOOGLE_SEARCH_ENGINE_ID);const base={provider:'Google Programmable Search',baseUrl:false,apiKey,engineId};
  if(!apiKey||!engineId)return{...base,liveRequest:'NOT ATTEMPTED',reason:!apiKey&&!engineId?'MISSING_API_KEY_AND_ENGINE_ID':!apiKey?'MISSING_API_KEY':'MISSING_ENGINE_ID'};
  const url=new URL('https://www.googleapis.com/customsearch/v1');url.search=new URLSearchParams({key:env.GOOGLE_SEARCH_API_KEY,cx:env.GOOGLE_SEARCH_ENGINE_ID,q:'"can\'t find old photo"',num:'1'}).toString();
  try{const response=await fetchImpl(url,{signal:AbortSignal.timeout(8000)});if(response.ok)return{...base,liveRequest:'PASS',reason:'NONE'};let reason=`HTTP_${response.status}`;try{const payload=await response.json();const code=payload?.error?.errors?.[0]?.reason||payload?.error?.status;if(code)reason=String(code).toUpperCase();}catch{}return{...base,liveRequest:'FAIL',reason};}catch(error){return{...base,liveRequest:'FAIL',reason:error?.name==='TimeoutError'?'TIMEOUT':'NETWORK_FAILURE'};}
}

if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const result=await webStatus();console.log(`PROVIDER: ${result.provider}`);if(result.provider==='SEARXNG'){console.log(`SEARXNG: ${result.searxng}`);console.log(`RAW RESULTS: ${result.rawResults}`);console.log(`HONORABLE RESULTS: ${result.honorableResults}`);}else{console.log('SEARXNG: NOT_CONFIGURED');console.log('RAW RESULTS: 0');console.log('HONORABLE RESULTS: 0');}console.log(`SAFE FAILURE: ${result.reason}`);}
